// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CCodeAI
{
    internal sealed partial class Vsix
    {
        public const string Id = "CCode.ee1b2319-5a85-4ecc-bc6e-4264f753f94e";
        public const string Name = "CCodeAI";
        public const string Description = @"Help you understand and optimize the code";
        public const string Language = "en-US";
        public const string Version = "2023.514.1";
        public const string Author = "TimChen";
        public const string Tags = "ChatGPT, Copilot, OpenAI, GPT4, GPT, Copilot X, Github Copilot";
    }
}
