// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CCodeAI
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CCodeAIString = "2bdd3495-3110-42a1-b16c-a967f03684a7";
        public static Guid CCodeAI = new Guid(CCodeAIString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CCodeMenu = 0x1001;
        public const int CCodeGroup = 0x1011;
        public const int CCodeExplainCommandId = 0x1021;
        public const int CCodeNoteCommandId = 0x1022;
        public const int CCodeOptimizeCommandId = 0x1023;
        public const int CCodeAddAskCommandId = 0x1024;
        public const int CCodeContinuationCodeCommandId = 0x1025;
        public const int CCodeAICommandId = 0x2001;
    }
}